# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('hash', models.CharField(max_length=64)),
                ('height', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('difficulty', models.FloatField()),
                ('previousblockhash', models.CharField(max_length=64)),
                ('nextblockhash', models.CharField(max_length=64)),
                ('chainwork', models.CharField(max_length=64)),
                ('transactions', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('coinbase_string', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlockStatistics',
            fields=[
                ('time', models.DateTimeField()),
                ('bin_start', models.IntegerField(primary_key=True, serialize=False)),
                ('segwit_average_2016', models.FloatField()),
                ('segwit_average_144', models.FloatField()),
                ('bip91_average_144', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('size', models.FloatField()),
                ('hashrate', models.FloatField()),
            ],
        ),
    ]
