# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodestats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='transactions_estimated',
            field=models.IntegerField(default=0),
        ),
    ]
