# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodestats', '0002_block_transactions_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockstatistics',
            name='transactions_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockstatistics',
            name='transactions_estimated_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
