# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodestats', '0003_auto_20180811_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockstatistics',
            name='transactions_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blockstatistics',
            name='transactions_estimated_day',
            field=models.IntegerField(default=0),
        ),
    ]
