"""
Django settings for Bitnodestats project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from .base import *

PRODUCTION = True
WSGI_PY_PATH = '/etc/uwsgi/vassals/bitnodestats.ini'

# SECURITY WARNING: don't run with debug turned on in production!
BITCOIN_CONF = '/home/bitcoin/.bitcoin/bitcoin.conf'
ALLOWED_HOSTS = ['domain.org']

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'bitnodestats',
#        'USER': 'bitnodestats',
#        'PASSWORD': '1234',
#        'HOST': '127.0.0.1',
#        'PORT': '',
#    }
#}

# manage.py collectstatic
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/bitnodestats/static/'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
